### ISSUE TITLE
key 和 secret 问题

### ISSUE THREAD

**Issue by RalfZhang** [zhanghai/DoubanYearProgress#2]
您好，我看到配置文件里有 
```
        key: '',
        secret: '',
```
这两项。
我也看到消息说 2015 年后豆瓣关闭了个人开发者的申请，而您的 YearProgerss 是 2017 年才创建。
我也想做一个试试，所以想请教下您这个 key 验证是怎么搞到的？
:)

**Comment by zhanghai** [comment]
不可描述，有需要的话请自己发掘。

**Comment by RalfZhang** [comment]
大概懂了，多谢
