### ISSUE TITLE
想问下，应该是怎么部署？

### ISSUE THREAD

**Issue by 0xzkzhao** [zhanghai/DoubanYearProgress#3]
对...
没玩过nodejs，不知道这个机器人咋用?

**Comment by zhanghai** [comment]
安装 nodejs 和 npm，目录下运行 npm install 然后 npm start；豆瓣 API Key/Secret 需要自行获取，不提供指导；其他问题请善用搜索引擎。

**Comment by 0xzkzhao** [comment]
@DreaminginCodeZH 已经搞明白了
原来是用了`node-schedule`来定时发布~
