### ISSUE TITLE
这个账号停发状态了

### ISSUE THREAD

**Issue by 9zer** [zhanghai/DoubanYearProgress#9]
你好，这个账号从5月15日就没有更新了，可能是账号需要验证

**Comment by zhanghai** [comment]
有两个原因，第一个是实名验证，我刚才解决了，但第二个是最近豆瓣的服务器在海外访问不稳定，`connect()` 经常 `ETIMEOUT`。我刚才试了几次后终于成功发出了一条测试广播。

目前姑且关闭这个 issue，如果明天十点还是没发出来请重新打开。

**Comment by 9zer** [comment]
昨天发出来了，但是今天又没有了

**Comment by zhanghai** [comment]
依然是豆瓣的国外节点问题，有时候会连不上。我姑且再重试了一次。
